import { createContext, ReactNode, useContext, useEffect, useMemo, useState } from 'react';

export type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const STORAGE_KEY = 'ft-language';

const translations: Record<Language, Record<string, string>> = {
  en: {},
  es: {
    Account: 'Cuenta',
    Active: 'Activos',
    'Active Goals': 'Metas activas',
    Aceptar: 'Aceptar',
    'Add Expense': 'Agregar gasto',
    'Already have an account?': 'Ya tienes una cuenta?',
    'Amount': 'Monto',
    'Additional notes...': 'Notas adicionales...',
    'All Categories': 'Todas las categorias',
    'All Months': 'Todos los meses',
    'Are you sure you want to remove this person? They will no longer have access to your financial data.': 'Seguro que quieres eliminar a esta persona? Ya no tendra acceso a tus datos financieros.',
    Calendar: 'Calendario',
    Cancel: 'Cancelar',
    Cash: 'Efectivo',
    Cards: 'Tarjetas',
    Category: 'Categoria',
    'Change Password': 'Cambiar contraseña',
    'Choose your preferred appearance': 'Elige tu apariencia preferida',
    'Click to add your first credit card': 'Toca para agregar tu primera tarjeta de credito',
    'Create Account': 'Crear cuenta',
    'Create account': 'Crear cuenta',
    'Create one': 'Crea una',
    'Create your account': 'Crea tu cuenta',
    Currency: 'Moneda',
    Dashboard: 'Panel',
    'Dark Mode': 'Modo oscuro',
    Date: 'Fecha',
    Debit: 'Debito',
    Delete: 'Eliminar',
    'Delete Expense': 'Eliminar gasto',
    Description: 'Descripcion',
    'Description (optional)': 'Descripcion (opcional)',
    'Display currency for amounts': 'Moneda para mostrar los montos',
    'Display Name': 'Nombre visible',
    'Display Name (optional)': 'Nombre visible (opcional)',
    'Edit Expense': 'Editar gasto',
    Email: 'Correo',
    'Email Address': 'Correo electronico',
    English: 'Inglés',
    Expenses: 'Gastos',
    'Failed to create account. Please try again.': 'No se pudo crear la cuenta. Intenta de nuevo.',
    'Failed to sign in with Google. Please try again.': 'No se pudo iniciar sesion con Google. Intenta de nuevo.',
    'Failed to sign up with Google. Please try again.': 'No se pudo registrar con Google. Intenta de nuevo.',
    'Failed to update profile.': 'No se pudo actualizar el perfil.',
    'Forgot password?': 'Olvidaste tu contraseña?',
    Friends: 'Amigos',
    'Full Name': 'Nombre completo',
    'Good afternoon': 'Buenas tardes',
    'Good evening': 'Buenas noches',
    'Good morning': 'Buenos dias',
    Goals: 'Metas',
    goals: 'metas',
    completed: 'completadas',
    "Here's your financial summary": 'Este es tu resumen financiero',
    Income: 'Ingresos',
    'Income vs Expenses Trend': 'Tendencia de ingresos vs gastos',
    'Invalid email or password. Please try again.': 'Correo o contraseña invalidos. Intenta de nuevo.',
    'Invite Friend': 'Invitar amigo',
    'Invite a Friend': 'Invitar a un amigo',
    'Invite someone to share your finances': 'Invita a alguien para compartir tus finanzas',
    'Invitaciones enviadas': 'Invitaciones enviadas',
    'Invitaciones recibidas': 'Invitaciones recibidas',
    Language: 'Idioma',
    'Credit Cards': 'Tarjetas de credito',
    Limit: 'Limite',
    'Light Mode': 'Modo claro',
    'Manage your account and preferences': 'Administra tu cuenta y preferencias',
    Method: 'Metodo',
    'Min 6 characters': 'Minimo 6 caracteres',
    'Monthly Expenses': 'Gastos del mes',
    'Monthly Income': 'Ingresos del mes',
    'New Password': 'Nueva contrasena',
    Name: 'Nombre',
    'New version installed': 'Nueva version instalada',
    'No cards registered': 'No hay tarjetas registradas',
    'No expenses found': 'No se encontraron gastos',
    'No expenses recorded this month': 'No hay gastos registrados este mes',
    'No expenses this month': 'No hay gastos este mes',
    'No friends added yet': 'Aun no has agregado amigos',
    'No name set': 'Sin nombre',
    'Or continue with': 'O continua con',
    'Or sign up with': 'O registrate con',
    Password: 'Contrasena',
    'Password changed successfully.': 'Contraseña actualizada correctamente.',
    'Password must be at least 6 characters.': 'La contraseña debe tener al menos 6 caracteres.',
    Preferences: 'Preferencias',
    Profile: 'Perfil',
    'Profile updated successfully.': 'Perfil actualizado correctamente.',
    'Recent Expenses': 'Gastos recientes',
    Remove: 'Eliminar',
    'Remove Friend': 'Eliminar amigo',
    Reports: 'Reportes',
    Salary: 'Ingresos',
    'Saving Goals': 'Metas de ahorro',
    Search: 'Buscar',
    'Search expenses...': 'Buscar gastos...',
    'Save Changes': 'Guardar cambios',
    Security: 'Seguridad',
    'Send Invitation': 'Enviar invitacion',
    'Share your financial overview with trusted people': 'Comparte tu resumen financiero con personas de confianza',
    'Shared Financial View': 'Vista financiera compartida',
    Settings: 'Configuracion',
    'Sign Out': 'Cerrar sesion',
    'Sign in': 'Iniciar sesion',
    'Sign in here': 'Inicia sesion aqui',
    'Sign in to your account': 'Inicia sesion en tu cuenta',
    'Sign in with Google': 'Iniciar con Google',
    'Sign up with Google': 'Registrarse con Google',
    'Signing in...': 'Iniciando sesion...',
    'Signing up...': 'Creando cuenta...',
    Spanish: 'Español',
    Statistics: 'Estadisticas',
    'Spending by Category': 'Gastos por categoria',
    'Start tracking your finances': 'Empieza a controlar tus finanzas',
    'Start your financial journey today': 'Empieza tu camino financiero hoy',
    'This email is already registered.': 'Este correo ya esta registrado.',
    'This person is already in your list.': 'Esta persona ya esta en tu lista.',
    Theme: 'Tema',
    Total: 'Total',
    Transfer: 'Transferencia',
    Credit: 'Credito',
    'Are you sure you want to delete this expense? This action cannot be undone.': 'Seguro que quieres eliminar este gasto? Esta accion no se puede deshacer.',
    'Coffee, Groceries...': 'Cafe, compras...',
    Clear: 'Limpiar',
    records: 'registros',
    Food: 'Comida',
    Transport: 'Transporte',
    Streaming: 'Streaming',
    Services: 'Servicios',
    Shopping: 'Compras',
    Health: 'Salud',
    Education: 'Educacion',
    Savings: 'Ahorros',
    Other: 'Otro',
    card: 'tarjeta',
    cards: 'tarjetas',
    there: 'ahi',
    'this month': 'este mes',
    'View-only access granted': 'Acceso de solo lectura concedido',
    'View summary': 'Ver resumen',
    'New friend request': 'Nueva solicitud de amistad',
    'Open Friends to accept or reject it.': 'Abre Amigos para aceptarla o rechazarla.',
    'Shared report from': 'Reporte compartido de',
    'You do not have access to this shared report.': 'No tienes acceso a este reporte compartido.',
    'Could not load this report.': 'No se pudo cargar este reporte.',
    'Ask your friend to send or accept the invitation first.': 'Pide a tu amigo que envie o acepte la invitacion primero.',
    'Welcome back': 'Bienvenido de nuevo',
    User: 'Usuario',
    "You can't add yourself.": 'No puedes agregarte a ti mismo.',
    'Your name': 'Tu nombre',
    'Current Password': 'Contraseña actual',
    'Save Profile': 'Guardar perfil',
    'New password must be at least 6 characters.': 'La nueva contraseña debe tener al menos 6 caracteres.',
    'Current password is incorrect.': 'La contraseña actual es incorrecta.',
    'Choose your preferred language': 'Elige tu idioma preferido',
    "Don't have an account?": 'No tienes una cuenta?',
    'Passwords do not match.': 'Las contraseñas no coinciden.',
    'Confirm Password': 'Confirmar contraseña',
    'Smart financial control at your fingertips': 'Control financiero inteligente en tus manos',
    'Activate web notifications to receive FinanceTrack alerts.': 'Activa las notificaciones web para recibir alertas de FinanceTrack.',
    'Allow notifications': 'Permitir notificaciones',
    'Requesting...': 'Solicitando...',
    'Notifications enabled': 'Notificaciones activadas',
    'FinanceTrack can now send you web alerts.': 'FinanceTrack ya puede enviarte alertas web.',
    'Enable notifications': 'Habilitar notificaciones',
    'Notifications enabled title': 'Notificaciones habilitadas',
    'Welcome to FinanceTrack': 'Bienvenido a FinanceTrack',
    'Organize your finances from one place. This mini tour shows you the essentials to get started.': 'Organiza tus finanzas desde un solo lugar. Este mini recorrido te muestra lo esencial para empezar.',
    'Income and expenses': 'Ingresos y gastos',
    'Track income, spending, and payment methods to see your real balance.': 'Registra entradas, salidas y metodos de pago para ver tu balance real.',
    CardsIntro: 'Tarjetas',
    'Manage limits, charges, and payments for your credit cards.': 'Controla limites, cargos y pagos de tus tarjetas de credito.',
    GoalsIntro: 'Metas',
    'Create saving goals and review your progress clearly.': 'Crea objetivos de ahorro y revisa tu avance con claridad.',
    FriendsIntro: 'Amigos',
    'Invite trusted people to share a read-only view.': 'Invita personas de confianza para compartir una vista solo lectura.',
    'Enable web notifications to hear about important changes or new releases.': 'Activa las notificaciones web para enterarte cuando haya cambios importantes o nuevas versiones.',
    Start: 'Empezar',
    'You moved from': 'Pasaste de',
    'Friends you invite can view your balance, expenses, and statistics, but they cannot edit or modify any data.': 'Los amigos que invites pueden ver tu balance, gastos y estadisticas, pero no pueden editar ni modificar datos.',
    'The invited person must already have a FinanceTrack account with that email.': 'La persona invitada debe tener una cuenta de FinanceTrack con ese correo.',
    'Quiere acceder a tu resumen financiero en modo lectura.': 'Quiere acceder a tu resumen financiero en modo lectura.',
    Rechazar: 'Rechazar',
    'Esperando respuesta': 'Esperando respuesta',
    'Your friend will see the invitation inside their Friends page. They can view your financial summary but cannot edit any data.': 'Tu amigo vera la invitacion dentro de su pagina de Amigos. Puede ver tu resumen financiero, pero no editar datos.',
    'to': 'a',
    'You already have the latest improvements.': 'Ya tienes las mejoras mas recientes.',
    January: 'Enero',
    February: 'Febrero',
    March: 'Marzo',
    April: 'Abril',
    May: 'Mayo',
    June: 'Junio',
    July: 'Julio',
    August: 'Agosto',
    September: 'Septiembre',
    October: 'Octubre',
    November: 'Noviembre',
    December: 'Diciembre',
    'Add Card': 'Agregar tarjeta',
    'Add Credit Card': 'Agregar tarjeta de credito',
    'Add Income': 'Agregar ingreso',
    'Add Funds': 'Agregar fondos',
    'Already Saved': 'Ya ahorrado',
    'Amount to Add': 'Monto a agregar',
    'Bank Name': 'Nombre del banco',
    'Base Salary': 'Salario base',
    'Monthly Salary':'Salario mensual',
    'Base salary only': 'Solo salario base',
    Bonus: 'Bono',
    bonus: 'Bono',
    Bonuses: 'Bonos',
    'Bonuses & Incentives': 'Bonos e incentivos',
    Car: 'Carro',
    'Card Color': 'Color de tarjeta',
    'Card Usage': 'Uso de tarjeta',
    'Click to create your first goal': 'Toca para crear tu primera meta',
    'Could not save the credit card. Please check your connection and try again.': 'No se pudo guardar la tarjeta. Revisa tu conexion e intenta de nuevo.',
    'Could not save the payment. Please check your connection and try again.': 'No se pudo guardar el pago. Revisa tu conexion e intenta de nuevo.',
    'Could not save the card usage. Please check your connection and try again.': 'No se pudo guardar el uso de tarjeta. Revisa tu conexion e intenta de nuevo.',
    'Could not delete the card. Please try again.': 'No se pudo eliminar la tarjeta. Intenta de nuevo.',
    'Create Goal': 'Crear meta',
    'Credit Card': 'Tarjeta de credito',
    'Credit Limit': 'Limite de credito',
    Cut: 'Corte',
    'Cut Date (day)': 'Fecha de corte (dia)',
    Day: 'Dia',
    day: 'dia',
    days: 'dias',
    'Days until payment': 'Dias para pagar',
    Deadline: 'Fecha limite',
    'Deadline (optional)': 'Fecha limite (opcional)',
    'Delete Card': 'Eliminar tarjeta',
    'Delete Goal': 'Eliminar meta',
    'Delete Record': 'Eliminar registro',
    Emergency: 'Emergencia',
    'Edit Card': 'Editar tarjeta',
    'Edit Goal': 'Editar meta',
    'Edit Income': 'Editar ingreso',
    goal: 'meta',
    'Goal Achieved!': 'Meta alcanzada!',
    'Goal Name': 'Nombre de la meta',
    Home: 'Casa',
    'Income History': 'Historial de ingresos',
    Incentive: 'Incentivo',
    incentive: 'Incentivo',
    'Last 4 digits': 'Ultimos 4 digitos',
    'Monthly Income Comparison': 'Comparacion mensual de ingresos',
    Month: 'Mes',
    'New Goal': 'Nueva meta',
    'New Saving Goal': 'Nueva meta de ahorro',
    'No income records yet. Add your first entry.': 'Aun no hay ingresos. Agrega tu primer registro.',
    'No saving goals yet': 'Aun no tienes metas de ahorro',
    'Note (optional)': 'Nota (opcional)',
    'Overall Progress': 'Progreso general',
    Pay: 'Pagar',
    Payment: 'Pago',
    'Payment Due Soon': 'Pago cercano',
    'Pay Date (day)': 'Fecha de pago (dia)',
    'Paid this month': 'Pagado este mes',
    'Pending balance': 'Balance pendiente',
    Progress: 'Progreso',
    'Recent Usage': 'Uso reciente',
    'Recent Payments': 'Pagos recientes',
    registered: 'registradas',
    'Register Usage': 'Registrar uso',
    'Register Payment': 'Registrar pago',
    Remaining: 'Restante',
    salary: 'Salario',
    saved: 'ahorrado',
    'Salary & Income': 'Salario e ingresos',
    'Target Amount': 'Monto objetivo',
    Technology: 'Tecnologia',
    'This Month': 'Este mes',
    'Total Saved': 'Total ahorrado',
    'Total Target': 'Meta total',
    'Track your salary, bonuses, and incentives': 'Controla tu salario, bonos e incentivos',
    Travel: 'Viaje',
    'Trip to Japan, Emergency Fund...': 'Viaje a Japon, fondo de emergencia...',
    'Used this month': 'Usado este mes',
    Use: 'Usar',
    Year: 'Ano',
    'Additional details...': 'Detalles adicionales...',
    'Groceries, fuel, subscription...': 'Compras, gasolina, suscripcion...',
    'This will permanently delete the card and all its payment records.': 'Esto eliminara permanentemente la tarjeta y todos sus registros de pago.',
    'This will permanently delete this saving goal.': 'Esto eliminara permanentemente esta meta de ahorro.',
    'Are you sure? This action cannot be undone.': 'Estas seguro? Esta accion no se puede deshacer.',
    'make sure to pay on time': 'asegurate de pagar a tiempo',
    'vs last month': 'vs mes anterior',
    'Annual financial reports and exports': 'Reportes financieros anuales y exportaciones',
    'Total Income': 'Ingresos totales',
    'Total Expenses': 'Gastos totales',
    'Net Savings': 'Ahorro neto',
    'Monthly Breakdown': 'Desglose mensual',
    'Savings Rate': 'Tasa de ahorro',
    Status: 'Estado',
    Positive: 'Positivo',
    Deficit: 'Deficit',
    'No data': 'Sin datos',
    'Annual Spending by Category': 'Gasto anual por categoria',
    'Analyze your financial patterns': 'Analiza tus patrones financieros',
    'Avg Monthly Expense': 'Gasto mensual promedio',
    'Spending Distribution': 'Distribucion de gastos',
    'No data for selected period': 'No hay datos para el periodo seleccionado',
    'Expenses by Category': 'Gastos por categoria',
    'Annual Financial Overview': 'Resumen financiero anual',
    Insights: 'Analisis',
    'Top Spending Category': 'Categoria con mayor gasto',
    'of income saved': 'de ingresos ahorrados',
    'Daily Average Spend': 'Gasto diario promedio',
    'per day this month': 'por dia este mes',
    Transactions: 'Transacciones',
    'Avg per Transaction': 'Promedio por transaccion',
    'average spend': 'gasto promedio',
    'vs. Monthly Average': 'vs promedio mensual',
    above: 'por encima del',
    below: 'por debajo del',
    average: 'promedio',
    'Financial Calendar': 'Calendario financiero',
    'Track payments, income and expenses': 'Controla pagos, ingresos y gastos',
    'payment due in': 'vence en',
    today: 'hoy',
    Today: 'Hoy',
    more: 'mas',
    Legend: 'Leyenda',
    Expense: 'Gasto',
    'Card Cut Date': 'Fecha de corte',
    'Card Payment': 'Pago de tarjeta',
    'Card Payments': 'Pagos de tarjetas',
    'Card Debt': 'Deuda de tarjetas',
    'Cash Outflow': 'Salida de efectivo',
    'Available Balance': 'Balance disponible',
    'Debt left': 'Deuda restante',
    'This month balance': 'Balance de este mes',
    'This Month Summary': 'Resumen de este mes',
    Sun: 'Dom',
    Mon: 'Lun',
    Tue: 'Mar',
    Wed: 'Mie',
    Thu: 'Jue',
    Fri: 'Vie',
    Sat: 'Sab',
    cut: 'corte',
    payment: 'pago',
    'Notifications unavailable': 'Notificaciones no disponibles',
    'Your browser does not support web notifications. Use Chrome, Firefox, Safari 16+, or Edge.': 'Tu navegador no soporta notificaciones web. Usa Chrome, Firefox, Safari 16+ o Edge.',
    'You will receive notifications about your account.': 'Recibiras notificaciones sobre tu cuenta.',
    'Web Notifications': 'Notificaciones web',
    'Notifications are enabled. You will receive alerts about account activity.': 'Notificaciones habilitadas. Recibiras alertas sobre movimientos en tu cuenta.',
    'Enable notifications to receive alerts about important transactions.': 'Activa las notificaciones para recibir alertas sobre transacciones importantes.',
    'Requesting permissions...': 'Solicitando permisos...',
    'Enable Notifications': 'Habilitar notificaciones',
    'You will receive notifications when:': 'Recibiras notificaciones cuando:',
    'A new expense or income is added': 'Se agregue un nuevo gasto o ingreso',
    'Data syncs in the background': 'Se sincronicen datos en segundo plano',
    'There are changes to your credit cards': 'Haya cambios en tus tarjetas de credito',
    'Why notifications?': 'Por que notificaciones?',
    'Notifications help you stay aware of your finances. You will receive real-time alerts about important account changes.': 'Las notificaciones te ayudan a estar atento a tus finanzas. Recibiras alertas en tiempo real sobre cambios importantes en tu cuenta.',
  },
};

const LanguageContext = createContext<LanguageContextType | null>(null);

function getInitialLanguage(): Language {
  const saved = localStorage.getItem(STORAGE_KEY);
  return saved === 'es' || saved === 'en' ? saved : 'en';
}

export function LanguageProvider({ children }: { readonly children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(getInitialLanguage);

  function setLanguage(nextLanguage: Language) {
    setLanguageState(nextLanguage);
    localStorage.setItem(STORAGE_KEY, nextLanguage);
  }

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: (key: string) => translations[language][key] || key,
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
